FROM node:12.17.0-alpine

# Env
ENV TIME_ZONE=Asia/Hong_Kong
ENV NODE_ENV=testing
ENV SERVER_PORT=80
ENV PROGRAM_VERSION=v${PROGRAM_VERSION}

# Timezone setting
RUN apk --update add tzdata \
   && cp /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime \
   && echo "Asia/Hong_Kong" > /etc/timezone \
   && apk del tzdata

# Create Directory for the Container
WORKDIR /usr/src/app

# Install all Packages
COPY package.json .
COPY package-lock.json .
RUN npm run build
RUN npm ci

# TypeScript
RUN npm run build
ADD ./build /usr/src/app

# Start
CMD [ "npm", "start" ]
EXPOSE 7050
