version: 4
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 0.5GB
    cpu_limit: 256
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "xxxxxx"
        - "xxxxx"
      security_groups:
        - "xxxxxx"
      assign_public_ip: ENABLED
